### ISSUE TITLE
Newly built instances not responding

### ISSUE THREAD

**Issue by j34ni** [norcams/iaas#24]
Hi,

I have been trying to build a new instance for a couple of hours, they seem to be spawn and running but I cannot access them with ssh.

I need it for a demo tomorrow and would appreciate if that worked quickly now, since I have to reinstall a lot of stuff.

Can you please have a look?

Thanks,

Jean

**Comment by furenest** [comment]
This is probably not an issue with the himlar-code. Please send an email to support@nrec.no or use the #iaas channel on uhps.slack.com. Our ssh documentation is a good read - https://docs.nrec.no/ssh.html and our docs on security groups is mandatory - https://docs.nrec.no/security-groups.html

**Comment by furenest** [comment]
not the place for user support
